### ISSUE TITLE
2.1.0 windows version is faulty

### ISSUE THREAD

**Issue by kingsrule2024** [VxBlocks/vxb_neptune_wallet#3]
2.1.0 installs fine but its UI is broken & it doesnt sync. Could the devs check this issue?

**Comment by kingsrule2024** [comment]
@kaola526 @code-pangolin Any ETA for 2.1.1?

**Comment by code-pangolin** [comment]
we are still investigating the ui issue, the ui works fine on macos,and we did not change ui since v2.0,  so it is very strange and will take time to find out why 😵 .

**Comment by code-pangolin** [comment]
fixed by https://github.com/VxBlocks/neptune-wallet-app/commit/e1084a94414f972c4f098824d8dacf5e8d6d9d47

**Comment by junfengZhong** [comment]
<img width="890" height="596" alt="Image" src="https://github.com/user-attachments/assets/18c0e692-0de5-498e-8c7d-413239665be7" />
2.1.1遇到无法发送NPT余额，该怎么解决

**Comment by txgtxid** [comment]
> <img alt="Image" width="890" height="596" src="https://private-user-images.githubusercontent.com/217159819/526264661-18c0e692-0de5-498e-8c7d-413239665be7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcwODMwMDYsIm5iZiI6MTc2NzA4MjcwNiwicGF0aCI6Ii8yMTcxNTk4MTkvNTI2MjY0NjYxLTE4YzBlNjkyLTBkZTUtNDk4ZS04YzdkLTQxMzIzOTY2NWJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIzMFQwODE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTU5ZGNmMjE0MjVkOWU4ZGFkYjU3YmIxMGFjZGI1Y2Y2ZDNjOWU0YmQ4ZjU4MmI5MGEzZGZjYzg4OTVjNWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AP5998jx2s2YCpWxMd1GJgNYa5wxMKibUERCd2wwJ84"> 2.1.1遇到无法发送NPT余额，该怎么解决

 I have the same problem

@code-pangolin  2.1.2 I still can't send it! What should I do?
